org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=GardenGals
plugin_name=Rustborn
plugin_description=All you can hear are the cries of the artificial souls left behind in the mechanical wastelands, echoes of the machines that were, the Rustborn are hunting you.
plugin_author=Kchem & coolbot, ©?Garden Gals
plugin_website=https://gardengals.carrd.co/

plugin_version=1.0.0
server_version=*
plugin_main_entrypoint=cool.bot.rustborn.Rustborn

