org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=GardenGals
plugin_name=Rustborn
plugin_description=Rustborn!
plugin_author=Kchem & coolbot, ©?Garden Gals
plugin_website=https://gardengals.carrd.co/

plugin_version=0.1.0
server_version=*
plugin_main_entrypoint=cool.bot.rustborn.Rustborn

